Repository optimizely/java-sdk, pull requests merged in 2020-07, with the labels that each got.

#379 Updated gradle version to gradle 6
  build.gradle
  core-httpclient-impl/src/test/java/com/optimizely/ab/OptimizelyHttpClientTest.java
  gradle/wrapper/gradle-wrapper.properties
Labels: :robot: 24 hrs

#385 ci: add source clear as a separate stage
  .travis.yml
Labels: :robot: 8 hrs

#382 ci: hook fps on travis
  .travis.yml
Labels: :robot: 16 hrs
